"""Render docs/workflows.md from the built-in catalog; --check fails when the file is stale."""

import argparse
import sys
from pathlib import Path

from tin_lite.catalog import BUILTIN_WORKFLOWS, WORKFLOW_SYSTEMS, BuiltinWorkflow

DOC_PATH = Path(__file__).resolve().parents[1] / "docs" / "workflows.md"
OTHER_SYSTEM = "General"


def cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def inputs(definition: dict) -> str:
    schema = definition["input_schema"]
    required = set(schema.get("required", ()))
    names = [name for name in schema.get("properties", {}) if name != "project_id"]
    if not names:
        return "—"
    return ", ".join(f"**`{name}`**" if name in required else f"`{name}`" for name in names)


def output(definition: dict) -> str:
    declared = (definition.get("procedure") or definition.get("code") or {}).get("output")
    if not declared:
        # A native flow that saves one fixed artifact pins its path in the definition.
        return f"`{definition['output_path']}`" if definition.get("output_path") else "—"
    path = declared.get("path") or declared.get("path_template")
    section = declared.get("section")
    if declared["kind"] == "github.pull_request":
        return f"Unmerged GitHub PR, receipt `{declared['receipt_path_template']}`"
    if section:
        return f"`{path}` ({section['heading'].lstrip('# ')} section)"
    return f"`{path}`"


def row(workflow: BuiltinWorkflow) -> str:
    definition = workflow.definition
    notes = []
    if workflow.kind != "workflow":
        notes.append(workflow.kind)
    if workflow.agent_only:
        notes.append("agent only")
    if workflow.review_policy is not None:
        notes.append("human review")
    title = cell(workflow.title) + (f" ({', '.join(notes)})" if notes else "")
    return (
        f"| {title}<br>`{workflow.key}` | {cell(workflow.description)} "
        f"| {inputs(definition)} | {output(definition)} |"
    )


def render() -> str:
    lines = [
        "# Built-in workflows",
        "",
        "<!-- Generated by scripts/dump_catalog.py from src/tin_lite/catalog.py. Do not edit. -->",
        "",
        f"Tin ships {len(BUILTIN_WORKFLOWS)} built-in workflows. Every workflow also takes a "
        "`project_id`; required inputs are **bold**. An output of — means the workflow saves "
        "its results through its own executor rather than one declared artifact.",
    ]
    systems = [(item.id, item.name) for item in WORKFLOW_SYSTEMS] + [(None, OTHER_SYSTEM)]
    for system_id, name in systems:
        workflows = [item for item in BUILTIN_WORKFLOWS if item.system == system_id]
        if not workflows:
            continue
        lines += [
            "",
            f"## {name}",
            "",
            "| Workflow | What it does | Inputs | Output |",
            "|---|---|---|---|",
            *(row(item) for item in workflows),
        ]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not DOC_PATH.exists() or DOC_PATH.read_text() != rendered:
            print(f"{DOC_PATH} is stale; run scripts/dump_catalog.py", file=sys.stderr)
            return 1
        return 0
    DOC_PATH.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
